//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 04:07:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.liverestaurant.com/OrderService/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.gallifreyan.ws.model;
