INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('ALBUMS_SEQ', 0);
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('PHOTOS_SEQ', 0);

--//@UNDO

DELETE from SEQUENCE WHERE SEQ_NAME IN ('ALBUMS_SEQ', 'PHOTOS_SEQ');