ALTER TABLE USERS_GROUPS ADD CONSTRAINT USERSGROUPS_USERID_FK FOREIGN KEY (USERID)
	REFERENCES USERS (USERID) ON DELETE CASCADE;
	
--//@UNDO
	
ALTER TABLE USERS_GROUPS DROP CONSTRAINT USERSGROUPS_USERID_FK;