ALTER TABLE USERS_GROUPS ADD CONSTRAINT USERSGROUPS_GROUPID_FK FOREIGN KEY (GROUPID)
	REFERENCES GROUPS (GROUPID)  ON DELETE CASCADE;

--//@UNDO

ALTER TABLE USERS_GROUPS DROP CONSTRAINT USERSGROUPS_GROUPID_FK;