package be.gallifreyan.javaee.registration.context;

public enum CollectionTestType
{
	ADD_NULL_TO_COLLECTION, ADD_ELEMENT_TO_COLLECTION, ADD_DUPLICATE_TO_COLLECTION, REMOVE_NULL_FROM_COLLECTION, REMOVE_ELEMENT_FROM_COLLECTION, REMOVE_NONEXISTENT_FROM_COLLECTION
}
